import { Point } from "@/types/points";

const points: Point[] = [
  {
    id: "rj-124",
    nome: "Base Comunitária da PM - Rocha Miranda",
    categoria: "seguranca",
    endereco: "Rua do Amparo, 45 - Rocha Miranda",
    bairro: "Rocha Miranda",
    lat: -22.8487,
    lng: -43.3342,
    horario: "24h",
    fonte: "Prefeitura RJ",
    verificado: true,
    atualizado_em: "2025-10-29",
  },
  {
    id: "rj-125",
    nome: "Escola Municipal Prof. Ana Neri",
    categoria: "educacao",
    endereco: "Rua Cerqueira Daltro, 210 - Honório Gurgel",
    bairro: "Honório Gurgel",
    lat: -22.8459,
    lng: -43.3531,
    horario: "07h-18h",
    fonte: "SEEDUC",
    verificado: true,
    atualizado_em: "2025-10-29",
  },
  {
    id: "rj-126",
    nome: "Clínica da Família Irajá",
    categoria: "saude",
    endereco: "Avenida Monsenhor Félix, 980 - Irajá",
    bairro: "Irajá",
    lat: -22.8315,
    lng: -43.3297,
    horario: "07h-22h",
    fonte: "OSM",
    verificado: false,
    atualizado_em: "2025-10-29",
  },
  {
    id: "rj-127",
    nome: "CRAS Madureira",
    categoria: "assistencia",
    endereco: "Rua Carolina Machado, 305 - Madureira",
    bairro: "Madureira",
    lat: -22.8732,
    lng: -43.3408,
    horario: "08h-17h",
    fonte: "SMASDH",
    verificado: true,
    atualizado_em: "2025-10-29",
  },
  {
    id: "rj-128",
    nome: "Wi-Fi Livre RJ - Praça de Rocha Miranda",
    categoria: "internet",
    endereco: "Praça Luiz Assumpção - Rocha Miranda",
    bairro: "Rocha Miranda",
    lat: -22.8526,
    lng: -43.3274,
    horario: "24h",
    fonte: "Wi-Fi Livre RJ",
    verificado: false,
    atualizado_em: "2025-10-29",
  },
];
export default points;
